
[package]
authors = ["zhouxinyong <samberxyz@gmail.com>"]
edition = "2021"
name    = "rs-zip"
version = "1.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
globset = "0.4"
napi = "3.0.0"
napi-derive = "3.0.0"
rayon = "1.10"
walkdir = "2.5"
zip = { version = "6.0.0", features = [
  "deflate",
  "deflate64",
  "bzip2",
  "zstd",
] }

[build-dependencies]
napi-build = "2"

[profile.release]
codegen-units = 1
lto           = true
opt-level     = 3
panic         = "abort"
strip         = "symbols"
