/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function unzip(sourcePath: string, outputDir: string): Promise<void>

/**
 * 暴露给 JS 的异步方法
 * options: { level: number, exclude: string[] }
 */
export declare function zip(
  sourceDir: string,
  outputPath: string,
  options?: ZipOptions | undefined | null,
): Promise<number>

export interface ZipOptions {
  level?: number
  exclude?: Array<string>
}
